[FOTOS]
CAMINHO=c:\develop\modelos\FINAL\FOTOS\
LOGON=c:\develop\modelos\fotos\

[PATH]
HELP=c:\develop\modelos\help\padrao.chm
lOGIX=[INFORMIX]Provider=Ifxoledbc;password=admin...;User ID=informix;Data Source=logix@ol_logix;Persist Security Info=true
LOGIXODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=ol_logix
MCODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=protheus 
CITACAO=c:\develop\modelos\datashare\citacao.mdb
CADMP04=c:\develop\modelos\mana5\EMP00001\
CADMP0499=c:\develop\modelos\mana5\EMP00099\
APP=c:\develop\modelos\wrpt\
DIC=c:\develop\modelos\DICION\DIC.mdb
ERRO=c:\develop\modelos\log\usulog.mdb
FOLHA=c:\develop\modelos\folha\
FOLHAEMP=c:\develop\modelos\folha\EMP00001\
FOLHAEMZ=c:\develop\modelos\folha\EMP000[ZZ]\
FOPTOEMP=c:\develop\modelos\folha\EMP00001\
FOPTOEMZ=c:\develop\modelos\folha\EMP000[ZZ]\
CEPS=c:\develop\modelos\cep\
ICONES=c:\develop\modelos\icones\
IE=c:\develop\modelos\CONTROLE\IE.MDB
IMG=c:\develop\modelos\DICION\
IMPREL=c:\develop\modelos\mana5\
SOMAANO=c:\develop\modelos\xsharpexe\Debug\
VORETRUN=c:\develop\modelos\xsharpexe\Debug\
MAIL=c:\develop\modelos\xsharpexe\Debug\
MAIL2=c:\develop\modelos\xsharpexe\Debug\
lstview=c:\develop\modelos\wrpt\
LOG=c:\develop\modelos\log\usulog.mdb
LOGCAM=c:\develop\modelos\log\
IMGMP04=c:\develop\modelos\PECAS\FMP04[ZZ].MDB
MAN=c:\develop\modelos\MAN\
MANA5=c:\develop\modelos\mana5\
MANA5BCO=c:\develop\modelos\banco\
MANA5BCO2=c:\develop\modelos\BANCORET2\
MANA5APU=c:\develop\modelos\APURA\
MANA5CON=c:\develop\modelos\mana5\configur\
MANA5CRM=c:\develop\modelos\CRM\
MANA5CRT=c:\develop\modelos\CONTROLE\
MANA5EMP=c:\develop\modelos\mana5\EMP00001\
MANA5EMZ=c:\develop\modelos\EMP000[ZZ]\
MANA5FER=c:\develop\modelos\ferramen\
MANA5FIS=c:\develop\modelos\FISCAL\
MANA5RH=c:\develop\modelos\RH\
MANA5FIN=c:\develop\modelos\FINAL\
MANA5GRA=c:\develop\modelos\GRAFICOS\
MANA5IMG=c:\develop\modelos\PECAS\
MANA5INS=c:\develop\modelos\INSTRUME\
MANA5PCP=c:\develop\modelos\pcp\
MANA5PRO=c:\develop\modelos\producao\
MANA5IAC=c:\develop\modelos\producao\
SINTELRNDTAB:=p:\totvs\mercador\tab\
MANA5NFE=c:\develop\modelos\nfe\
PLUGINREL=c:\develop\modelos\wrpt\
MANA5QUA=c:\develop\modelos\QUALIDA\
MANA5TGQ=c:\develop\modelos\TGQ\
MANA5VIA=c:\develop\modelos\viabili\
MANARQ=manaMAN
MANCAM=c:\develop\modelos\mana5\configur\
MANTEM=S
MDB=c:\develop\modelos\wrpt\
RELAT=c:\develop\modelos\wrpt\
RPT=c:\develop\modelos\wrpt\rpts\
RET=c:\develop\modelos\wrpt\rets\
PLG=c:\develop\modelos\wrpt\rpts\
RTF=c:\develop\modelos\wrpt\docs\
FOL=c:\develop\modelos\wrpt\rpts\
INT=c:\develop\modelos\wrpt\rpts\
USER=c:\develop\modelos\wrpt\WRPT.MDB
TABUSER=c:\develop\modelos\wrpt\WRPT.MDB
USR=c:\develop\modelos\wrpt\WRPT.MDB
sysuser=c:\develop\modelos\wrpt\WRPT.MDB
WRPT=c:\develop\modelos\wrpt\WRPT.MDB
SYSCONF=c:\develop\modelos\wrpt\SYSCONF.MDB
USALX=NAO
USAMC=NAO

[EMAIL]
SERVER=

[ODBCCFG]
ODBCCFG001=IMAGEM|Fotos Produtos|c:\develop\modelos\imagens\IMAGEM.MDB|MDB
ODBCCFG002=IMGFER|Fotos Ferramentas|c:\develop\modelos\PECAS\IMGFER.MDB|MDB
ODBCCFG003=IMGMA01|Fotos Clientes|c:\develop\modelos\PECAS\IMGMA01.MDB|MDB
ODBCCFG004=IMGME01|Fotos Maquinas|c:\develop\modelos\PECAS\IMGME01.MDB|MDB
ODBCCFG005=IMGME04|fotos Instrumentos|c:\develop\modelos\PECAS\IMGME04.MDB|MDB
ODBCCFG006=IMGME06|Fotos Utilitarios|c:\develop\modelos\PECAS\IMGME06.MDB|MDB
ODBCCFG007=FEMEA|Controle|c:\develop\modelos\controle\FEMEA.MDB|MDB
ODBCCFG008=PFP|Controle|c:\develop\modelos\controle\PFP.MDB|MDB
ODBCCFG009=IMGMQ01|Fotos sub Produtos|c:\develop\modelos\PECAS\IMGMQ01.MDB|MDB
ODBCCFG010=IMGMR01|Fotos embalagens|c:\develop\modelos\PECAS\IMGMR01.MDB|MDB
ODBCCFG011=IMGMS01|Fotos Produtos|c:\develop\modelos\imagens\IMAGEM.MDB|MDB
ODBCCFG012=IMGMT01|Fotos Componentes|c:\develop\modelos\PECAS\IMGMT01.MDB|MDB
ODBCCFG013=IMGMU01|Fotos Materia Prima|c:\develop\modelos\PECAS\IMGMU01.MDB|MDB
ODBCCFG014=IMGMW05|Fotos consumiveis|c:\develop\modelos\PECAS\IMGMW05.MDB|MDB
ODBCCFG015=IMGMW07|Fotos Itens Manutencao|c:\develop\modelos\PECAS\IMGMW07.MDB|MDB
ODBCCFG016=MANA5|MANA5|c:\develop\modelos\|DBF
ODBCCFG017=MANA5APU|MANA5 Apuracao|c:\develop\modelos\apura\|DBF
ODBCCFG018=MANA5BCO|MANA5 Banco|c:\develop\modelos\banco\|DBF
ODBCCFG019=MANA5CON|MANA5 configur|c:\develop\modelos\mana5\configur\|DBF
ODBCCFG020=MANA5CRM|MANA5 CRM|c:\develop\modelos\crm\|DBF
ODBCCFG021=MANA5FIS|MANA5 Fiscal|c:\develop\modelos\fiscal\|DBF
ODBCCFG022=MANA5GRA|MANA5 Graficos|c:\develop\modelos\graficos\|DBF
ODBCCFG023=MANA5INS|MANA5 Instrumentos|c:\develop\modelos\instrume\|DBF
ODBCCFG024=MANA5PCP|MANA5 PCP|c:\develop\modelos\pcp\|DBF
ODBCCFG025=MANA5PRO|MANA5 Producao|c:\develop\modelos\producao\|DBF
ODBCCFG026=MANA5QUA|MANA5 Qualidade|c:\develop\modelos\qualida\|DBF
ODBCCFG027=MANA5RH|MANA5 RH|c:\develop\modelos\rh\|DBF
ODBCCFG028=MANA5TGQ|MANA5 TGQ|c:\develop\modelos\tgq\|DBF
ODBCCFG029=MANA5VIA|MANA5 Viabilidade|c:\develop\modelos\viabili\|DBF
ODBCCFG030=PF|Controle|c:\develop\modelos\controle\PF.MDB|MDB
ODBCCFG031=DESENHO|Controle|c:\develop\modelos\controle\DESENHO.MDB|MDB
ODBCCFG032=POA|Controle|c:\develop\modelos\controle\POA.MDB|MDB
ODBCCFG033=PFG|Controle|c:\develop\modelos\controle\PFG.MDB|MDB
ODBCCFG034=MANA5FER|MANA5 Ferramental|c:\develop\modelos\ferramen\|DBF
ODBCCFG035=MANA5ENG|MANA5 Engenharia|c:\develop\modelos\engenha\|DBF
;Compatibilidade
ODBCCFG036=MANA5EMP|MANA5 empresa|c:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG037=MANA5EM1|MANA5 empresa 1|c:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG038=FOLHAEM1|folha empresa 1|c:\develop\modelos\folha\emp00001\|DBF
ODBCCFG039=FOPTOEM1|folha ponto empresa 1|c:\develop\modelos\folha\emp00001\|DBF
;folha
ODBCCFG040=FOLHA|folha|c:\develop\modelos\folha\|DBF
ODBCCFG041=FOLHAPTO|Folha Ponto|c:\develop\modelos\folha\|DBF
ODBCCFG042=FOLHAEMP|folha Empresa Padrao|c:\develop\modelos\folha\emp00001\|DBF
ODBCCFG043=FOPTOEMP|folha Ponto Empresa Padrao|c:\develop\modelos\folha\emp00001\|DBF
;empresas mamemp
ODBCCFG044=MANEMP01|MANA5 empresa 01|c:\develop\modelos\mana5\EMP00001\|DBF
;fotos empresa CPF
ODBCCFG045=FMP0401|Fotos Funcionarios 01|c:\develop\modelos\PECAS\FMP04CPF.MDB|MDB
;folha emp
ODBCCFG046=FOLEMP01|folha empresa 01|c:\develop\modelos\folha\emp00001\|DBF
;folha ptoemp
ODBCCFG047=PTOEMP01|folha empresa 01|c:\develop\modelos\folha\emp00001\|DBF


[CITACAO]
