[FOTOS]
CAMINHO=d:\develop\modelos\FINAL\FOTOS\
LOGON=d:\develop\modelos\fotos\

[PATH]
HELP=d:\develop\modelos\help\padrao.chm
lOGIX=[INFORMIX]Provider=Ifxoledbc;password=sena;User ID=informix;Data Source=logix@logix;Persist Security Info=true
LOGIXODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=logix
MCODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=protheus 
CITACAO_mdb=d:\develop\modelos\datashare\citacao.sqlite
CITACAO_sqlite=d:\develop\modelos\datashare\citacao.sqlite
CITACAO_mariadb=localhost.3306.mariadb.citacao
CITACAO_mysql=localhost.3306.mysql.citacao
CITACAO=d:\develop\modelos\datashare\citacao.sqlite
CADMP04=d:\develop\modelos\mana5\EMP00001\
CADMP0499=d:\develop\modelos\mana5\EMP00099\
APP=d:\develop\modelos\wrpt\
DIC=d:\develop\modelos\DICION\DIC.sqlite
ERRO=d:\develop\modelos\log\usulog.sqlite
FOLHA=d:\develop\modelos\folha\
FOLHAEMP=d:\develop\modelos\folha\EMP00001\
FOLHAEMZ=d:\develop\modelos\folha\EMP000[ZZ]\
FOPTOEMP=d:\develop\modelos\folha\EMP00001\
FOPTOEMZ=d:\develop\modelos\folha\EMP000[ZZ]\
CEPS=d:\develop\modelos\cep\
ICONES=d:\develop\modelos\icones\
IE=d:\develop\modelos\CONTROLE\IE.sqlite
IMG=d:\develop\modelos\DICION\
IMPREL=d:\develop\modelos\mana5\
SOMAANO=d:\develop\modelos\xsharpexe\Debug\
VORETRUN=d:\develop\modelos\xsharpexe\Debug\
MAIL=d:\develop\modelos\xsharpexe\Debug\
MAIL2=d:\develop\modelos\xsharpexe\Debug\
lstview=d:\develop\modelos\wrpt\
LOG=d:\develop\modelos\log\usulog.sqlite
LOGCAM=d:\develop\modelos\log\
IMGMP04=d:\develop\modelos\PECAS\FMP04[ZZ].sqlite
MAN=d:\develop\modelos\MAN\
MANA5=d:\develop\modelos\mana5\
MANA5BCO=d:\develop\modelos\banco\
MANA5BCO2=d:\develop\modelos\BANCORET2\
MANA5APU=d:\develop\modelos\APURA\
MANA5CON=d:\develop\modelos\mana5\configur\
MANA5CRM=d:\develop\modelos\CRM\
MANA5CRT=d:\develop\modelos\CONTROLE\
MANA5EMP=d:\develop\modelos\mana5\EMP00001\
MANA5EMZ=d:\develop\modelos\EMP000[ZZ]\
MANA5FER=d:\develop\modelos\ferramen\
MANA5FIS=d:\develop\modelos\FISCAL\
MANA5RH=d:\develop\modelos\RH\
MANA5FIN=d:\develop\modelos\FINAL\
MANA5GRA=d:\develop\modelos\GRAFICOS\
MANA5IMG=d:\develop\modelos\PECAS\
MANA5INS=d:\develop\modelos\INSTRUME\
MANA5PCP=d:\develop\modelos\pcp\
MANA5PRO=d:\develop\modelos\producao\
MANA5IAC=d:\develop\modelos\producao\
SINTELRNDTAB:=p:\totvs\mercador\tab\
MANA5NFE=d:\develop\modelos\nfe\
PLUGINREL=d:\develop\modelos\wrpt\
MANA5QUA=d:\develop\modelos\QUALIDA\
MANA5TGQ=d:\develop\modelos\TGQ\
MANA5VIA=d:\develop\modelos\viabili\
MANARQ=manaMAN
MANCAM=d:\develop\modelos\mana5\configur\
MANTEM=S
MDB=d:\develop\modelos\wrpt\wrpt.sqlite
RELAT=d:\develop\modelos\wrpt\
RPT=d:\develop\modelos\wrpt\RPT.sqlite
DOC=d:\develop\modelos\wrpt\RTF.sqlite
FOL=d:\develop\modelos\wrpt\RPTFOL.sqlite
INT=d:\develop\modelos\wrpt\RPTINT.sqlite
RET=d:\develop\modelos\wrpt\rets\
PLG=d:\develop\modelos\wrpt\rpts\
RTF=d:\develop\modelos\wrpt\docs\
USER=d:\develop\modelos\wrpt\WRPT.sqlite
TABUSER=d:\develop\modelos\wrpt\WRPT.sqlite
USR=d:\develop\modelos\wrpt\WRPT.sqlite
sysuser=d:\develop\modelos\wrpt\WRPT.sqlite
WRPT=d:\develop\modelos\wrpt\WRPT.sqlite
SYSCONF=d:\develop\modelos\wrpt\SYSCONF.sqlite
USALX=NAO
USAMC=NAO

[EMAIL]
SERVER=

[ODBCCFG]
ODBCCFG001=IMAGEM|Fotos Produtos|d:\develop\modelos\imagens\IMAGEM.sqlite|SQLITE
ODBCCFG002=IMGFER|Fotos Ferramentas|d:\develop\modelos\PECAS\IMGFER.sqlite|SQLITE
ODBCCFG003=IMGMA01|Fotos Clientes|d:\develop\modelos\PECAS\IMGMA01.sqlite|SQLITE
ODBCCFG004=IMGME01|Fotos Maquinas|d:\develop\modelos\PECAS\IMGME01.sqlite|SQLITE
ODBCCFG005=IMGME04|fotos Instrumentos|d:\develop\modelos\PECAS\IMGME04.sqlite|SQLITE
ODBCCFG006=IMGME06|Fotos Utilitarios|d:\develop\modelos\PECAS\IMGME06.sqlite|SQLITE
ODBCCFG007=FEMEA|Controle|d:\develop\modelos\controle\FEMEA.sqlite|SQLITE
ODBCCFG008=PFP|Controle|d:\develop\modelos\controle\PFP.sqlite|SQLITE
ODBCCFG009=IMGMQ01|Fotos sub Produtos|d:\develop\modelos\PECAS\IMGMQ01.sqlite|SQLITE
ODBCCFG010=IMGMR01|Fotos embalagens|d:\develop\modelos\PECAS\IMGMR01.sqlite|SQLITE
ODBCCFG011=IMGMS01|Fotos Produtos|d:\develop\modelos\imagens\IMAGEM.sqlite|SQLITE
ODBCCFG012=IMGMT01|Fotos Componentes|d:\develop\modelos\PECAS\IMGMT01.sqlite|SQLITE
ODBCCFG013=IMGMU01|Fotos Materia Prima|d:\develop\modelos\PECAS\IMGMU01.sqlite|SQLITE
ODBCCFG014=IMGMW05|Fotos consumiveis|d:\develop\modelos\PECAS\IMGMW05.sqlite|SQLITE
ODBCCFG015=IMGMW07|Fotos Itens Manutencao|d:\develop\modelos\PECAS\IMGMW07.sqlite|SQLITE
ODBCCFG016=MANA5|MANA5|d:\develop\modelos\|DBF
ODBCCFG017=MANA5APU|MANA5 Apuracao|d:\develop\modelos\apura\|DBF
ODBCCFG018=MANA5BCO|MANA5 Banco|d:\develop\modelos\banco\|DBF
ODBCCFG019=MANA5CON|MANA5 configur|d:\develop\modelos\mana5\configur\|DBF
ODBCCFG020=MANA5CRM|MANA5 CRM|d:\develop\modelos\crm\|DBF
ODBCCFG021=MANA5FIS|MANA5 Fiscal|d:\develop\modelos\fiscal\|DBF
ODBCCFG022=MANA5GRA|MANA5 Graficos|d:\develop\modelos\graficos\|DBF
ODBCCFG023=MANA5INS|MANA5 Instrumentos|d:\develop\modelos\instrume\|DBF
ODBCCFG024=MANA5PCP|MANA5 PCP|d:\develop\modelos\pcp\|DBF
ODBCCFG025=MANA5PRO|MANA5 Producao|d:\develop\modelos\producao\|DBF
ODBCCFG026=MANA5QUA|MANA5 Qualidade|d:\develop\modelos\qualida\|DBF
ODBCCFG027=MANA5RH|MANA5 RH|d:\develop\modelos\rh\|DBF
ODBCCFG028=MANA5TGQ|MANA5 TGQ|d:\develop\modelos\tgq\|DBF
ODBCCFG029=MANA5VIA|MANA5 Viabilidade|d:\develop\modelos\viabili\|DBF
ODBCCFG030=PF|Controle|d:\develop\modelos\controle\PF.sqlite|SQLITE
ODBCCFG031=DESENHO|Controle|d:\develop\modelos\controle\DESENHO.sqlite|SQLITE
ODBCCFG032=POA|Controle|d:\develop\modelos\controle\POA.sqlite|SQLITE
ODBCCFG033=PFG|Controle|d:\develop\modelos\controle\PFG.sqlite|SQLITE
ODBCCFG034=MANA5FER|MANA5 Ferramental|d:\develop\modelos\ferramen\|DBF
ODBCCFG035=MANA5ENG|MANA5 Engenharia|d:\develop\modelos\engenha\|DBF
;Compatibilidade
ODBCCFG036=MANA5EMP|MANA5 empresa|d:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG037=MANA5EM1|MANA5 empresa 1|d:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG038=FOLHAEM1|folha empresa 1|d:\develop\modelos\folha\emp00001\|DBF
ODBCCFG039=FOPTOEM1|folha ponto empresa 1|d:\develop\modelos\folha\emp00001\|DBF
;folha
ODBCCFG040=FOLHA|folha|d:\develop\modelos\folha\|DBF
ODBCCFG041=FOLHAPTO|Folha Ponto|d:\develop\modelos\folha\|DBF
ODBCCFG042=FOLHAEMP|folha Empresa Padrao|d:\develop\modelos\folha\emp00001\|DBF
ODBCCFG043=FOPTOEMP|folha Ponto Empresa Padrao|d:\develop\modelos\folha\emp00001\|DBF
;empresas mamemp
ODBCCFG044=MANEMP01|MANA5 empresa 01|d:\develop\modelos\mana5\EMP00001\|DBF
;fotos empresa CPF
ODBCCFG045=FMP0401|Fotos Funcionarios 01|d:\develop\modelos\PECAS\FMP04CPF.sqlite|SQLITE
;folha emp
ODBCCFG046=FOLEMP01|folha empresa 01|d:\develop\modelos\folha\emp00001\|DBF
;folha ptoemp
ODBCCFG047=PTOEMP01|folha empresa 01|d:\develop\modelos\folha\emp00001\|DBF


[CITACAO]
ADMIN=N                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
