[FOTOS]
CAMINHO=c:\develop\modelos\FINAL\FOTOS\
LOGON=c:\develop\modelos\RH\FOTOS0001\

[HELP]
CAMINHO=c:\develop\modelos\HELP\padrao.chm
HELPTXT=c:\develop\modelos\help\controle.txt


[PATH]
HELP=c:\develop\modelos\help\padrao.chm
HELPTXT=c:\develop\modelos\help\controle.txt
lstview=c:\develop\modelos\wrpt\
lOGIX=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=logix@prd_a;Persist Security Info=true
LOGIXODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=ol_logix 
MICROSIGA=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=protheus@prd_a;Persist Security Info=true
MICROSIGAODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=protheus
MICROSIGADBF=c:\develop\modelos\SINTEGRA\
CADMP04=c:\develop\modelos\mana5\EMP00001\
CADMP0499=c:\develop\modelos\mana5\EMP00099\
CITACAO=c:\develop\modelos\wrpt\CITACAO.MDB
DESENHO=c:\develop\modelos\CONTROLE\DESENHO.MDB
MDB=c:\develop\modelos\CONTROLE\CONTROLE.MDB
ERRO=c:\develop\modelos\log\usulog.mdb
USR=c:\develop\modelos\CONTROLE\CONTROLE.MDB
POA=c:\develop\modelos\CONTROLE\POA.MDB
POKA=c:\develop\modelos\CONTROLE\POA.MDB
DISPO=c:\develop\modelos\CONTROLE\POA.MDB
FEMEA=c:\develop\modelos\CONTROLE\FEMEA.MDB
FEMEAPAD=c:\develop\modelos\CONTROLE\FEMEA.MDB
FEMEAPF=c:\develop\modelos\CONTROLE\PF.MDB
IE=c:\develop\modelos\CONTROLE\IE.MDB
SINTEGRA=c:\develop\modelos\nfe\nfesped\
PF=c:\develop\modelos\CONTROLE\PF.MDB
PFP=c:\develop\modelos\CONTROLE\PFP.MDB
PFG=c:\develop\modelos\CONTROLE\PFG.MDB
PPAP=c:\develop\modelos\CONTROLE\PPAP.MDB
APP=c:\develop\modelos\CONTROLE\
IMG=c:\develop\modelos\DICION\
CEPS=c:\develop\modelos\cep\
CNPJIEUF=c:\develop\modelos\CNPJIEUF\
USER=c:\develop\modelos\controle\CONTROLE.MDB
DIC=c:\develop\modelos\DICION\DIC.mdb
RPT=c:\develop\modelos\wrpt\
RET=c:\develop\modelos\wrpt\
PLG=c:\develop\modelos\wrpt\
RTF=c:\develop\modelos\wrpt\
FOL=c:\develop\modelos\wrpt\
INT=c:\develop\modelos\wrpt\
WRPT=c:\develop\modelos\wrpt\WRPT.MDB
CONTROLE=c:\develop\modelos\controle\CONTROLE.MDB
WRPTX=c:\develop\modelos\wrpt\
RELAT=c:\develop\modelos\wrpt\
MANA5APU=c:\develop\modelos\APURA\
MANA5CON=c:\develop\modelos\mana5\configur\
MANA5CRM=c:\develop\modelos\CRM\
MANA5CRT=c:\develop\modelos\CONTROLE\
MANA5EMP=c:\develop\modelos\mana5\EMP00001\
MANA5EMZ=c:\develop\modelos\EMP0000[Z]\
MANA5EMPSDE=[SDECDX]c:\develop\modelos\mana5\EMP00001\
MANA5EMPFOX=[JETFOX]c:\develop\modelos\mana5\EMP00001\
MANA5FER=c:\develop\modelos\ferramen\
MANA5FIS=c:\develop\modelos\FISCAL\
MANA5FIN=c:\develop\modelos\FINAL\
MANA5GRA=c:\develop\modelos\GRAFICOS\
MANA5IMG=c:\develop\modelos\PECAS\
MANA5INS=c:\develop\modelos\INSTRUME\
MANA5PCP=c:\develop\modelos\pcp\
MANA5PRO=c:\develop\modelos\producao\
MANA5QUA=c:\develop\modelos\QUALIDA\
MANA5TGQ=c:\develop\modelos\TGQ\
MANA5VIA=c:\develop\modelos\viabili\
ICONES=c:\develop\modelos\ICONES\
LOGOMS01=c:\develop\modelos\PECAS\
LOGOMA01=c:\develop\modelos\PECAS\
LOGOFER=c:\develop\modelos\PECAS\
LOGOME01=c:\develop\modelos\PECAS\
LOGOME04=c:\develop\modelos\PECAS\
LOGOME06=c:\develop\modelos\PECAS\
LOGOMU01=c:\develop\modelos\PECAS\
LOGOMT01=c:\develop\modelos\PECAS\
LOGOMW05=c:\develop\modelos\PECAS\
LOGOMR01=c:\develop\modelos\PECAS\
IMGFER=c:\develop\modelos\PECAS\IMGFER.MDB
IMGMA01=c:\develop\modelos\PECAS\IMGMA01.MDB
IMGME01=c:\develop\modelos\PECAS\IMGME01.MDB
IMGME04=c:\develop\modelos\PECAS\IMGME04.MDB
IMGME06=c:\develop\modelos\PECAS\IMGME06.MDB
IMGMP04=c:\develop\modelos\PECAS\FMP04[ZZ].MDB
IMGMP04CPF:=c:\develop\modelos\PECAS\FMP04CPF.MDB
IMGMR01=c:\develop\modelos\PECAS\IMGMR01.MDB
IMGMS01=c:\develop\modelos\pecas\IMAGEM.MDB
IMGMT01=c:\develop\modelos\PECAS\IMGMT01.MDB
IMGMU01=c:\develop\modelos\PECAS\IMGMU01.MDB
IMGMW05=c:\develop\modelos\PECAS\IMGMW05.MDB
IMGMW07=c:\develop\modelos\PECAS\IMGMW07.MDB
IMGMQ01=c:\develop\modelos\PECAS\IMGMQ01.MDB
SYSCONF=c:\develop\modelos\wrpt\SYSCONF.MDB
TABUSER=c:\develop\modelos\CONTROLE\CONTROLE.MDB
SYSUSER=c:\develop\modelos\CONTROLE\CONTROLE.MDB
LOG=c:\develop\modelos\log\usulog.mdb
LOGCAM=c:\develop\modelos\log\wrpt\
MANA5CON=c:\develop\modelos\mana5\configur\
IMPREL=c:\develop\modelos\mana5\
SOMAANO=c:\develop\modelos\xsharpexe\Debug\
VORETRUN=c:\develop\modelos\xsharpexe\Debug\
MAIL=c:\develop\modelos\xsharpexe\Debug\
MAIL2=c:\develop\modelos\xsharpexe\Debug\
MANTEM=N
MANARQ=manaAMAN
MANCAM=c:\develop\modelos\configur
MAN=c:\develop\modelos\MAN\
USALX=NAO
USAMC=NAO


[SAC.DBF]
CAMINHO=c:\develop\modelos\TGQ\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=SAC.CDX
TAG0=SAC
INDEX0=SAC
TAG1=SAC-2
INDEX1=STR(OS,8,2)+STR(NF,8)+STR(ITEM,3)
TAG2=SAC-3
INDEX2=CODIGO

[EMAIL]
SERVER=
PORTA=
FROM=
USUARIO=
SENHA=
POP=
FEM00001=;
PF000001=;
PPAP0001=;
PROT0001=;
PROT0002=;
PC000001=;
PCI00001=;
PFS00001=;
PFS00002=;

[ODBCCFG]
ODBCCFG001=IMAGEM|Fotos Produtos|c:\develop\modelos\pecas\IMAGEM.MDB|MDB
ODBCCFG002=IMGFER|Fotos Ferramentas|c:\develop\modelos\PECAS\IMGFER.MDB|MDB
ODBCCFG003=IMGMA01|Fotos Clientes|c:\develop\modelos\PECAS\IMGMA01.MDB|MDB
ODBCCFG004=IMGME01|Fotos Maquinas|c:\develop\modelos\PECAS\IMGME01.MDB|MDB
ODBCCFG005=IMGME04|fotos Instrumentos|c:\develop\modelos\PECAS\IMGME04.MDB|MDB
ODBCCFG006=IMGME06|Fotos Utilitarios|c:\develop\modelos\PECAS\IMGME06.MDB|MDB
ODBCCFG007=FEMEA|Controle|c:\develop\modelos\controle\FEMEA.MDB|MDB
ODBCCFG008=PFP|Controle|c:\develop\modelos\controle\PFP.MDB|MDB
ODBCCFG009=IMGMQ01|Fotos sub Produtos|c:\develop\modelos\PECAS\IMGMQ01.MDB|MDB
ODBCCFG010=IMGMR01|Fotos embalagens|c:\develop\modelos\PECAS\IMGMR01.MDB|MDB
ODBCCFG011=IMGMS01|Fotos Produtos|c:\develop\modelos\pecas\IMAGEM.MDB|MDB
ODBCCFG012=IMGMT01|Fotos Componentes|c:\develop\modelos\PECAS\IMGMT01.MDB|MDB
ODBCCFG013=IMGMU01|Fotos Materia Prima|c:\develop\modelos\PECAS\IMGMU01.MDB|MDB
ODBCCFG014=IMGMW05|Fotos consumiveis|c:\develop\modelos\PECAS\IMGMW05.MDB|MDB
ODBCCFG015=IMGMW07|Fotos Itens Manutencao|c:\develop\modelos\PECAS\IMGMW07.MDB|MDB
ODBCCFG016=MANA5|MANA5|c:\develop\modelos\|DBF
ODBCCFG017=MANA5APU|MANA5 Apuracao|c:\develop\modelos\apura\|DBF
ODBCCFG018=MANA5BCO|MANA5 Banco|c:\develop\modelos\banco\|DBF
ODBCCFG019=MANA5CON|MANA5 configur|c:\develop\modelos\mana5\configur\|DBF
ODBCCFG020=MANA5CRM|MANA5 CRM|c:\develop\modelos\crm\|DBF
ODBCCFG021=MANA5FIS|MANA5 Fiscal|c:\develop\modelos\fiscal\|DBF
ODBCCFG022=MANA5GRA|MANA5 Graficos|c:\develop\modelos\graficos\|DBF
ODBCCFG023=MANA5INS|MANA5 Instrumentos|c:\develop\modelos\instrume\|DBF
ODBCCFG024=MANA5PCP|MANA5 PCP|c:\develop\modelos\pcp\|DBF
ODBCCFG025=MANA5PRO|MANA5 Producao|c:\develop\modelos\producao\|DBF
ODBCCFG026=MANA5QUA|MANA5 Qualidade|c:\develop\modelos\qualida\|DBF
ODBCCFG027=MANA5RH|MANA5 RH|c:\develop\modelos\rh\|DBF
ODBCCFG028=MANA5TGQ|MANA5 TGQ|c:\develop\modelos\tgq\|DBF
ODBCCFG029=MANA5VIA|MANA5 Viabilidade|c:\develop\modelos\viabili\|DBF
ODBCCFG030=PF|Controle|c:\develop\modelos\controle\PF.MDB|MDB
ODBCCFG031=DESENHO|Controle|c:\develop\modelos\controle\DESENHO.MDB|MDB
ODBCCFG032=POA|Controle|c:\develop\modelos\controle\POA.MDB|MDB
ODBCCFG033=PFG|Controle|c:\develop\modelos\controle\PFG.MDB|MDB
ODBCCFG034=MANA5FER|MANA5 Ferramental|c:\develop\modelos\ferramen\|DBF
ODBCCFG035=MANA5ENG|MANA5 Engenharia|c:\develop\modelos\engenha\|DBF
;Compatibilidade
ODBCCFG036=MANA5EMP|MANA5 empresa|c:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG037=MANA5EM1|MANA5 empresa 1|c:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG038=FOLHAEM1|folha empresa 1|c:\develop\modelos\folha\emp00001\|DBF
ODBCCFG039=FOPTOEM1|folha ponto empresa 1|c:\develop\modelos\folha\emp00001\|DBF
;folha
ODBCCFG040=FOLHA|folha|c:\develop\modelos\folha\|DBF
ODBCCFG041=FOLHAPTO|Folha Ponto|c:\develop\modelos\folha\|DBF
ODBCCFG042=FOLHAEMP|folha Empresa Padrao|c:\develop\modelos\folha\emp00001\|DBF
ODBCCFG043=FOPTOEMP|folha Ponto Empresa Padrao|c:\develop\modelos\folha\emp00001\|DBF
;empresas mamemp
ODBCCFG044=MANEMP01|MANA5 empresa 01|c:\develop\modelos\mana5\EMP00001\|DBF
;fotos empresa CPF
ODBCCFG045=FMP0401|Fotos Funcionarios 01|c:\develop\modelos\PECAS\FMP04CPF.MDB|MDB
;folha emp
ODBCCFG046=FOLEMP01|folha empresa 01|c:\develop\modelos\folha\emp00001\|DBF
;folha ptoemp
ODBCCFG047=PTOEMP01|folha empresa 01|c:\develop\modelos\folha\emp00001\|DBF

[CITACAO]
ADMIN=N                                                                                                                                                                                                                                                              
