[FOTOS]
CAMINHO=d:\develop\modelos\FINAL\FOTOS\
LOGON=d:\develop\modelos\RH\FOTOS0001\

[HELP]
CAMINHO=d:\develop\modelos\HELP\padrao.chm
HELPTXT=d:\develop\modelos\help\controle.txt


[PATH]
HELP=d:\develop\modelos\help\padrao.chm
HELPTXT=d:\develop\modelos\help\controle.txt
lstview=d:\develop\modelos\wrpt\
lOGIX=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=logix@prd_a;Persist Security Info=true
LOGIXODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=ol_logix 
MICROSIGA=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=protheus@prd_a;Persist Security Info=true
MICROSIGAODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=protheus
MICROSIGADBF=d:\develop\modelos\SINTEGRA\
CADMP04=d:\develop\modelos\mana5\EMP00001\
CADMP0499=d:\develop\modelos\mana5\EMP00099\
CITACAO=d:\develop\modelos\wrpt\CITACAO.sqlite
DESENHO=d:\develop\modelos\CONTROLE\DESENHO.sqlite
MDB=d:\develop\modelos\CONTROLE\controle.sqlite
ERRO=d:\develop\modelos\log\usulog.sqlite
USR=d:\develop\modelos\CONTROLE\CONTROLE.sqlite
POA=d:\develop\modelos\CONTROLE\POA.sqlite
POKA=d:\develop\modelos\CONTROLE\POA.sqlite
DISPO=d:\develop\modelos\CONTROLE\POA.sqlite
FEMEA=d:\develop\modelos\CONTROLE\FEMEA.sqlite
FEMEAPAD=d:\develop\modelos\CONTROLE\FEMEA.sqlite
FEMEAPF=d:\develop\modelos\CONTROLE\PF.sqlite
IE=d:\develop\modelos\CONTROLE\IE.sqlite
SINTEGRA=d:\develop\modelos\nfe\nfesped\
PF=d:\develop\modelos\CONTROLE\PF.sqlite
PFP=d:\develop\modelos\CONTROLE\PFP.sqlite
PFG=d:\develop\modelos\CONTROLE\PFG.sqlite
PPAP=d:\develop\modelos\CONTROLE\PPAP.sqlite
APP=d:\develop\modelos\CONTROLE\
IMG=d:\develop\modelos\DICION\
CEPS=d:\develop\modelos\cep\
CNPJIEUF=d:\develop\modelos\CNPJIEUF\
USER=d:\develop\modelos\controle\CONTROLE.sqlite
DIC=d:\develop\modelos\DICION\DIC.sqlite
RET=d:\develop\modelos\wrpt\rets\
PLG=d:\develop\modelos\wrpt\rpts\
RTF=d:\develop\modelos\wrpt\docs\
RPT=d:\develop\modelos\wrpt\RPT.sqlite
FOL=d:\develop\modelos\wrpt\RPTFOL.sqlite
INT=d:\develop\modelos\wrpt\RPTINT.sqlite
DOC=d:\develop\modelos\wrpt\RTF.sqlite
WRPT=d:\develop\modelos\wrpt\WRPT.sqlite
CONTROLE=d:\develop\modelos\controle\CONTROLE.sqlite
WRPTX=d:\develop\modelos\wrpt\
RELAT=d:\develop\modelos\wrpt\
MANA5APU=d:\develop\modelos\APURA\
MANA5CON=d:\develop\modelos\mana5\configur\
MANA5CRM=d:\develop\modelos\CRM\
MANA5CRT=d:\develop\modelos\CONTROLE\
MANA5EMP=d:\develop\modelos\mana5\EMP00001\
MANA5EMZ=d:\develop\modelos\EMP0000[Z]\
MANA5EMPSDE=[SDECDX]d:\develop\modelos\mana5\EMP00001\
MANA5EMPFOX=[JETFOX]d:\develop\modelos\mana5\EMP00001\
MANA5FER=d:\develop\modelos\ferramen\
MANA5FIS=d:\develop\modelos\FISCAL\
MANA5FIN=d:\develop\modelos\FINAL\
MANA5GRA=d:\develop\modelos\GRAFICOS\
MANA5IMG=d:\develop\modelos\PECAS\
MANA5INS=d:\develop\modelos\INSTRUME\
MANA5PCP=d:\develop\modelos\pcp\
MANA5PRO=d:\develop\modelos\producao\
MANA5QUA=d:\develop\modelos\QUALIDA\
MANA5TGQ=d:\develop\modelos\TGQ\
MANA5VIA=d:\develop\modelos\viabili\
ICONES=d:\develop\modelos\ICONES\
LOGOMS01=d:\develop\modelos\PECAS\
LOGOMA01=d:\develop\modelos\PECAS\
LOGOFER=d:\develop\modelos\PECAS\
LOGOME01=d:\develop\modelos\PECAS\
LOGOME04=d:\develop\modelos\PECAS\
LOGOME06=d:\develop\modelos\PECAS\
LOGOMU01=d:\develop\modelos\PECAS\
LOGOMT01=d:\develop\modelos\PECAS\
LOGOMW05=d:\develop\modelos\PECAS\
LOGOMR01=d:\develop\modelos\PECAS\
IMGFER=d:\develop\modelos\PECAS\IMGFER.sqlite
IMGMA01=d:\develop\modelos\PECAS\IMGMA01.sqlite
IMGME01=d:\develop\modelos\PECAS\IMGME01.sqlite
IMGME04=d:\develop\modelos\PECAS\IMGME04.sqlite
IMGME06=d:\develop\modelos\PECAS\IMGME06.sqlite
IMGMP04=d:\develop\modelos\PECAS\FMP04[ZZ].sqlite
IMGMP04CPF:=d:\develop\modelos\PECAS\FMP04CPF.sqlite
IMGMR01=d:\develop\modelos\PECAS\IMGMR01.sqlite
IMGMS01=d:\develop\modelos\pecas\IMAGEM.sqlite
IMGMT01=d:\develop\modelos\PECAS\IMGMT01.sqlite
IMGMU01=d:\develop\modelos\PECAS\IMGMU01.sqlite
IMGMW05=d:\develop\modelos\PECAS\IMGMW05.sqlite
IMGMW07=d:\develop\modelos\PECAS\IMGMW07.sqlite
IMGMQ01=d:\develop\modelos\PECAS\IMGMQ01.sqlite
SYSCONF=d:\develop\modelos\wrpt\SYSCONF.sqlite
TABUSER=d:\develop\modelos\CONTROLE\CONTROLE.sqlite
SYSUSER=d:\develop\modelos\CONTROLE\CONTROLE.sqlite
LOG=d:\develop\modelos\log\usulog.sqlite
LOGCAM=d:\develop\modelos\log\controle\
MANA5CON=d:\develop\modelos\mana5\configur\
IMPREL=d:\develop\modelos\mana5\
SOMAANO=d:\develop\modelos\xsharpexe\Debug\
VORETRUN=d:\develop\modelos\xsharpexe\Debug\
MAIL=d:\develop\modelos\xsharpexe\Debug\
MAIL2=d:\develop\modelos\xsharpexe\Debug\
MANTEM=N
MANARQ=manaAMAN
MANCAM=d:\develop\modelos\configur
MAN=d:\develop\modelos\MAN\
USALX=NAO
USAMC=NAO


[SAC.DBF]
CAMINHO=d:\develop\modelos\TGQ\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=SAC.CDX
TAG0=SAC
INDEX0=SAC
TAG1=SAC-2
INDEX1=STR(OS,8,2)+STR(NF,8)+STR(ITEM,3)
TAG2=SAC-3
INDEX2=CODIGO

[EMAIL]
SERVER=
PORTA=
FROM=
USUARIO=
SENHA=
POP=
FEM00001=;
PF000001=;
PPAP0001=;
PROT0001=;
PROT0002=;
PC000001=;
PCI00001=;
PFS00001=;
PFS00002=;

[ODBCCFG]
ODBCCFG001=IMAGEM|Fotos Produtos|d:\develop\modelos\pecas\IMAGEM.sqlite|SQLITE
ODBCCFG002=IMGFER|Fotos Ferramentas|d:\develop\modelos\PECAS\IMGFER.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG003=IMGMA01|Fotos Clientes|d:\develop\modelos\PECAS\IMGMA01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG004=IMGME01|Fotos Maquinas|d:\develop\modelos\PECAS\IMGME01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG005=IMGME04|fotos Instrumentos|d:\develop\modelos\PECAS\IMGME04.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG006=IMGME06|Fotos Utilitarios|d:\develop\modelos\PECAS\IMGME06.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG007=FEMEA|Controle|d:\develop\modelos\controle\FEMEA.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG008=PFP|Controle|d:\develop\modelos\controle\PFP.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG009=IMGMQ01|Fotos sub Produtos|d:\develop\modelos\PECAS\IMGMQ01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG010=IMGMR01|Fotos embalagens|d:\develop\modelos\PECAS\IMGMR01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG011=IMGMS01|Fotos Produtos|d:\develop\modelos\pecas\IMAGEM.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG012=IMGMT01|Fotos Componentes|d:\develop\modelos\PECAS\IMGMT01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG013=IMGMU01|Fotos Materia Prima|d:\develop\modelos\PECAS\IMGMU01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG014=IMGMW05|Fotos consumiveis|d:\develop\modelos\PECAS\IMGMW05.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG015=IMGMW07|Fotos Itens Manutencao|d:\develop\modelos\PECAS\IMGMW07.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG016=MANA5|MANA5|d:\develop\modelos\|DBF
ODBCCFG017=MANA5APU|MANA5 Apuracao|d:\develop\modelos\apura\|DBF
ODBCCFG018=MANA5BCO|MANA5 Banco|d:\develop\modelos\banco\|DBF
ODBCCFG019=MANA5CON|MANA5 configur|d:\develop\modelos\mana5\configur\|DBF
ODBCCFG020=MANA5CRM|MANA5 CRM|d:\develop\modelos\crm\|DBF
ODBCCFG021=MANA5FIS|MANA5 Fiscal|d:\develop\modelos\fiscal\|DBF
ODBCCFG022=MANA5GRA|MANA5 Graficos|d:\develop\modelos\graficos\|DBF
ODBCCFG023=MANA5INS|MANA5 Instrumentos|d:\develop\modelos\instrume\|DBF
ODBCCFG024=MANA5PCP|MANA5 PCP|d:\develop\modelos\pcp\|DBF
ODBCCFG025=MANA5PRO|MANA5 Producao|d:\develop\modelos\producao\|DBF
ODBCCFG026=MANA5QUA|MANA5 Qualidade|d:\develop\modelos\qualida\|DBF
ODBCCFG027=MANA5RH|MANA5 RH|d:\develop\modelos\rh\|DBF
ODBCCFG028=MANA5TGQ|MANA5 TGQ|d:\develop\modelos\tgq\|DBF
ODBCCFG029=MANA5VIA|MANA5 Viabilidade|d:\develop\modelos\viabili\|DBF
ODBCCFG030=PF|Controle|d:\develop\modelos\controle\PF.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG031=DESENHO|Controle|d:\develop\modelos\controle\DESENHO.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG032=POA|Controle|d:\develop\modelos\controle\POA.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG033=PFG|Controle|d:\develop\modelos\controle\PFG.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG034=MANA5FER|MANA5 Ferramental|d:\develop\modelos\ferramen\|DBF
ODBCCFG035=MANA5ENG|MANA5 Engenharia|d:\develop\modelos\engenha\|DBF
;Compatibilidade
ODBCCFG036=MANA5EMP|MANA5 empresa|d:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG037=MANA5EM1|MANA5 empresa 1|d:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG038=FOLHAEM1|folha empresa 1|d:\develop\modelos\folha\emp00001\|DBF
ODBCCFG039=FOPTOEM1|folha ponto empresa 1|d:\develop\modelos\folha\emp00001\|DBF
;folha
ODBCCFG040=FOLHA|folha|d:\develop\modelos\folha\|DBF
ODBCCFG041=FOLHAPTO|Folha Ponto|d:\develop\modelos\folha\|DBF
ODBCCFG042=FOLHAEMP|folha Empresa Padrao|d:\develop\modelos\folha\emp00001\|DBF
ODBCCFG043=FOPTOEMP|folha Ponto Empresa Padrao|d:\develop\modelos\folha\emp00001\|DBF
;empresas mamemp
ODBCCFG044=MANEMP01|MANA5 empresa 01|d:\develop\modelos\mana5\EMP00001\|DBF
;fotos empresa CPF
ODBCCFG045=FMP0401|Fotos Funcionarios 01|d:\develop\modelos\PECAS\FMP04CPF.sqlite|SQLITE
;folha emp
ODBCCFG046=FOLEMP01|folha empresa 01|d:\develop\modelos\folha\emp00001\|DBF
;folha ptoemp
ODBCCFG047=PTOEMP01|folha empresa 01|d:\develop\modelos\folha\emp00001\|DBF

[CITACAO]
ADMIN=N                                                                                                                                                                                                                                                              
