[FOTOS]
CAMINHO=d:\develop\modelos\FINAL\FOTOS\
LOGON=C:\develop\modelos\RH\FOTOS0001\

[HELP]
CAMINHO=C:\develop\modelos\HELP\padrao.chm
HELPTXT=C:\develop\modelos\help\controle_alteracoes.md
HELPMD=\develop\modelos\help\banco\controle.md

[PATH]
HELP=C:\develop\modelos\help\padrao.chm
HELPTXT=C:\develop\modelos\help\controle.md
lstview=C:\develop\modelos\wrpt\
lOGIX=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=logix@prd_a;Persist Security Info=true
LOGIXODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=ol_logix 
MICROSIGA=[INFORMIX]Provider=Ifxoledbc;password=informix;User ID=informix;Data Source=protheus@prd_a;Persist Security Info=true
MICROSIGAODBC=[CONN]Provider=MSDASQL.1;Persist Security Info=False;Data Source=protheus
MICROSIGADBF=C:\develop\modelos\SINTEGRA\
CADMP04=C:\develop\modelos\mana5\EMP00001\
CADMP0499=C:\develop\modelos\mana5\EMP00099\
CITACAO_mdb=C:\develop\modelos\datashare\citacao.sqlite
CITACAO_sqlite=C:\develop\modelos\datashare\citacao.sqlite
CITACAO_mariadb=localhost.3306.mariadb.citacao
CITACAO_mysql=localhost.3306.mysql.citacao
CITACAO=C:\develop\modelos\datashare\citacao.sqlite
DESENHO=C:\develop\modelos\CONTROLE\DESENHO.sqlite
MDB=C:\develop\modelos\CONTROLE\controle.sqlite
ERRO=C:\develop\modelos\log\usulog.sqlite
USR=C:\develop\modelos\CONTROLE\CONTROLE.sqlite
POA=C:\develop\modelos\CONTROLE\POA.sqlite
POKA=C:\develop\modelos\CONTROLE\POA.sqlite
DISPO=C:\develop\modelos\CONTROLE\POA.sqlite
FEMEA=C:\develop\modelos\CONTROLE\FEMEA.sqlite
FEMEAPAD=C:\develop\modelos\CONTROLE\FEMEA.sqlite
FEMEAPF=C:\develop\modelos\CONTROLE\PF.sqlite
IE=C:\develop\modelos\CONTROLE\IE.sqlite
SINTEGRA=C:\develop\modelos\nfe\nfesped\
PF=C:\develop\modelos\CONTROLE\PF.sqlite
PFP=C:\develop\modelos\CONTROLE\PFP.sqlite
PFG=C:\develop\modelos\CONTROLE\PFG.sqlite
PPAP=C:\develop\modelos\CONTROLE\PPAP.sqlite
APP=C:\develop\modelos\CONTROLE\
IMG=C:\develop\modelos\DICION\
CEPS=C:\develop\modelos\cep\
CNPJIEUF=C:\develop\modelos\CNPJIEUF\
USER=C:\develop\modelos\controle\CONTROLE.sqlite
DIC=C:\develop\modelos\DICION\DIC.sqlite
RET=C:\develop\modelos\wrpt\rets\
PLG=C:\develop\modelos\wrpt\rpts\
RTF=C:\develop\modelos\wrpt\docs\
RPT=C:\develop\modelos\wrpt\RPT.sqlite
FOL=C:\develop\modelos\wrpt\RPTFOL.sqlite
INT=C:\develop\modelos\wrpt\RPTINT.sqlite
DOC=C:\develop\modelos\wrpt\RTF.sqlite
WRPT=C:\develop\modelos\wrpt\WRPT.sqlite
CONTROLE=C:\develop\modelos\controle\CONTROLE.sqlite
WRPTX=C:\develop\modelos\wrpt\
RELAT=C:\develop\modelos\wrpt\
MANA5APU=C:\develop\modelos\APURA\
MANA5CON=C:\develop\modelos\mana5\configur\
MANA5CRM=C:\develop\modelos\CRM\
MANA5CRT=C:\develop\modelos\CONTROLE\
MANA5EMP=C:\develop\modelos\mana5\EMP00001\
MANA5EMZ=C:\develop\modelos\EMP0000[Z]\
MANA5EMPSDE=[SDECDX]C:\develop\modelos\mana5\EMP00001\
MANA5EMPFOX=[JETFOX]C:\develop\modelos\mana5\EMP00001\
MANA5FER=C:\develop\modelos\ferramen\
MANA5FIS=C:\develop\modelos\FISCAL\
MANA5FIN=C:\develop\modelos\FINAL\
MANA5GRA=C:\develop\modelos\GRAFICOS\
MANA5IMG=C:\develop\modelos\PECAS\
MANA5INS=C:\develop\modelos\INSTRUME\
MANA5PCP=C:\develop\modelos\pcp\
MANA5PRO=C:\develop\modelos\producao\
MANA5QUA=C:\develop\modelos\QUALIDA\
MANA5TGQ=C:\develop\modelos\TGQ\
MANA5VIA=C:\develop\modelos\viabili\
ICONES=C:\develop\modelos\ICONES\
LOGOMS01=C:\develop\modelos\PECAS\
LOGOMA01=C:\develop\modelos\PECAS\
LOGOFER=C:\develop\modelos\PECAS\
LOGOME01=C:\develop\modelos\PECAS\
LOGOME04=C:\develop\modelos\PECAS\
LOGOME06=C:\develop\modelos\PECAS\
LOGOMU01=C:\develop\modelos\PECAS\
LOGOMT01=C:\develop\modelos\PECAS\
LOGOMW05=C:\develop\modelos\PECAS\
LOGOMR01=C:\develop\modelos\PECAS\
IMGFER=C:\develop\modelos\PECAS\IMGFER.sqlite
IMGMA01=C:\develop\modelos\PECAS\IMGMA01.sqlite
IMGME01=C:\develop\modelos\PECAS\IMGME01.sqlite
IMGME04=C:\develop\modelos\PECAS\IMGME04.sqlite
IMGME06=C:\develop\modelos\PECAS\IMGME06.sqlite
IMGMP04=C:\develop\modelos\PECAS\FMP04[ZZ].sqlite
IMGMP04CPF:=C:\develop\modelos\PECAS\FMP04CPF.sqlite
IMGMR01=C:\develop\modelos\PECAS\IMGMR01.sqlite
IMGMS01=C:\develop\modelos\pecas\IMAGEM.sqlite
IMGMT01=C:\develop\modelos\PECAS\IMGMT01.sqlite
IMGMU01=C:\develop\modelos\PECAS\IMGMU01.sqlite
IMGMW05=C:\develop\modelos\PECAS\IMGMW05.sqlite
IMGMW07=C:\develop\modelos\PECAS\IMGMW07.sqlite
IMGMQ01=C:\develop\modelos\PECAS\IMGMQ01.sqlite
SYSCONF=C:\develop\modelos\wrpt\SYSCONF.sqlite
TABUSER=C:\develop\modelos\CONTROLE\CONTROLE.sqlite
SYSUSER=C:\develop\modelos\CONTROLE\CONTROLE.sqlite
LOG=C:\develop\modelos\log\usulog.sqlite
LOGCAM=C:\develop\modelos\log\controle\
MANA5CON=C:\develop\modelos\mana5\configur\
IMPREL=C:\develop\modelos\mana5\
SOMAANO=C:\develop\modelos\xsharpexe\Debug\
VORETRUN=C:\develop\modelos\xsharpexe\Debug\
MAIL=C:\develop\modelos\xsharpexe\Debug\
MAIL2=C:\develop\modelos\xsharpexe\Debug\
MANTEM=N
MANARQ=manaAMAN
MANCAM=C:\develop\modelos\configur
MAN=C:\develop\modelos\MAN\
USALX=NAO
USAMC=NAO


[SAC.DBF]
CAMINHO=C:\develop\modelos\TGQ\
DRIVER=DBFCDX
NUMMAINTAINED=3
MAINTAIN0=SAC.CDX
TAG0=SAC
INDEX0=SAC
TAG1=SAC-2
INDEX1=STR(OS,8,2)+STR(NF,8)+STR(ITEM,3)
TAG2=SAC-3
INDEX2=CODIGO

[EMAIL]
SERVER=
PORTA=
FROM=
USUARIO=
SENHA=
POP=
FEM00001=;
PF000001=;
PPAP0001=;
PROT0001=;
PROT0002=;
PC000001=;
PCI00001=;
PFS00001=;
PFS00002=;

[ODBCCFG]
ODBCCFG001=IMAGEM|Fotos Produtos|C:\develop\modelos\pecas\IMAGEM.sqlite|SQLITE
ODBCCFG002=IMGFER|Fotos Ferramentas|C:\develop\modelos\PECAS\IMGFER.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG003=IMGMA01|Fotos Clientes|C:\develop\modelos\PECAS\IMGMA01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG004=IMGME01|Fotos Maquinas|C:\develop\modelos\PECAS\IMGME01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG005=IMGME04|fotos Instrumentos|C:\develop\modelos\PECAS\IMGME04.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG006=IMGME06|Fotos Utilitarios|C:\develop\modelos\PECAS\IMGME06.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG007=FEMEA|Controle|C:\develop\modelos\controle\FEMEA.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG008=PFP|Controle|C:\develop\modelos\controle\PFP.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG009=IMGMQ01|Fotos sub Produtos|C:\develop\modelos\PECAS\IMGMQ01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG010=IMGMR01|Fotos embalagens|C:\develop\modelos\PECAS\IMGMR01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG011=IMGMS01|Fotos Produtos|C:\develop\modelos\pecas\IMAGEM.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG012=IMGMT01|Fotos Componentes|C:\develop\modelos\PECAS\IMGMT01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG013=IMGMU01|Fotos Materia Prima|C:\develop\modelos\PECAS\IMGMU01.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG014=IMGMW05|Fotos consumiveis|C:\develop\modelos\PECAS\IMGMW05.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG015=IMGMW07|Fotos Itens Manutencao|C:\develop\modelos\PECAS\IMGMW07.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG016=MANA5|MANA5|C:\develop\modelos\|DBF
ODBCCFG017=MANA5APU|MANA5 Apuracao|C:\develop\modelos\apura\|DBF
ODBCCFG018=MANA5BCO|MANA5 Banco|C:\develop\modelos\banco\|DBF
ODBCCFG019=MANA5CON|MANA5 configur|C:\develop\modelos\mana5\configur\|DBF
ODBCCFG020=MANA5CRM|MANA5 CRM|C:\develop\modelos\crm\|DBF
ODBCCFG021=MANA5FIS|MANA5 Fiscal|C:\develop\modelos\fiscal\|DBF
ODBCCFG022=MANA5GRA|MANA5 Graficos|C:\develop\modelos\graficos\|DBF
ODBCCFG023=MANA5INS|MANA5 Instrumentos|C:\develop\modelos\instrume\|DBF
ODBCCFG024=MANA5PCP|MANA5 PCP|C:\develop\modelos\pcp\|DBF
ODBCCFG025=MANA5PRO|MANA5 Producao|C:\develop\modelos\producao\|DBF
ODBCCFG026=MANA5QUA|MANA5 Qualidade|C:\develop\modelos\qualida\|DBF
ODBCCFG027=MANA5RH|MANA5 RH|C:\develop\modelos\rh\|DBF
ODBCCFG028=MANA5TGQ|MANA5 TGQ|C:\develop\modelos\tgq\|DBF
ODBCCFG029=MANA5VIA|MANA5 Viabilidade|C:\develop\modelos\viabili\|DBF
ODBCCFG030=PF|Controle|C:\develop\modelos\controle\PF.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG031=DESENHO|Controle|C:\develop\modelos\controle\DESENHO.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG032=POA|Controle|C:\develop\modelos\controle\POA.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG033=PFG|Controle|C:\develop\modelos\controle\PFG.sqlite|SQLITE.sqlite|SQLITE
ODBCCFG034=MANA5FER|MANA5 Ferramental|C:\develop\modelos\ferramen\|DBF
ODBCCFG035=MANA5ENG|MANA5 Engenharia|C:\develop\modelos\engenha\|DBF
;Compatibilidade
ODBCCFG036=MANA5EMP|MANA5 empresa|C:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG037=MANA5EM1|MANA5 empresa 1|C:\develop\modelos\mana5\EMP00001\|DBF
ODBCCFG038=FOLHAEM1|folha empresa 1|C:\develop\modelos\folha\emp00001\|DBF
ODBCCFG039=FOPTOEM1|folha ponto empresa 1|C:\develop\modelos\folha\emp00001\|DBF
;folha
ODBCCFG040=FOLHA|folha|C:\develop\modelos\folha\|DBF
ODBCCFG041=FOLHAPTO|Folha Ponto|C:\develop\modelos\folha\|DBF
ODBCCFG042=FOLHAEMP|folha Empresa Padrao|C:\develop\modelos\folha\emp00001\|DBF
ODBCCFG043=FOPTOEMP|folha Ponto Empresa Padrao|C:\develop\modelos\folha\emp00001\|DBF
;empresas mamemp
ODBCCFG044=MANEMP01|MANA5 empresa 01|C:\develop\modelos\mana5\EMP00001\|DBF
;fotos empresa CPF
ODBCCFG045=FMP0401|Fotos Funcionarios 01|C:\develop\modelos\PECAS\FMP04CPF.sqlite|SQLITE
;folha emp
ODBCCFG046=FOLEMP01|folha empresa 01|C:\develop\modelos\folha\emp00001\|DBF
;folha ptoemp
ODBCCFG047=PTOEMP01|folha empresa 01|C:\develop\modelos\folha\emp00001\|DBF

ODBCCFG048=MANA5FIN|MANA5 FINAL|C:\develop\modelos\FINAL\|DBF
ODBCCFG049=CEPS|CEPS|C:\develop\modelos\FINAL\|DBF
ODBCCFG050=CNPJIEUF|CNPJIEUF|C:\develop\modelos\FINAL\|DBF


[CITACAO]
ADMIN=N         

[EMAILINT]
ADMIN=N                                                                                                                                                                                                                                                          
